### ISSUE TITLE
Exporting AD Objects by creation date

### ISSUE THREAD

**Issue by Arbelac** [jaols/ADExportImport#3]
Hi,

Can I export AD user and/or group by date creation? I want to add start and end date parameters in your script. is it possible?

Kind Regards,

**Comment by jaols** [comment]
Yes. As all the Export-files has an option for LDAPfilter you may use that to limit the exported objects. To export object created during 2022 you could use this LDAPFilter (not tested):

 "(&(whenCreated>=20220101000000.0Z)(whenCreated<=20221231235959.0Z))"

https://learn.microsoft.com/en-us/windows/win32/adschema/s-string-generalized-time
