### ISSUE TITLE
Setting different passwords for each user account

### ISSUE THREAD

**Issue by Arbelac** [jaols/ADExportImport#4]
Hi,

Normally , I have been running my script like below. but this script sets the same password for all users.

.\Import-AdUsers.ps1 -ImportFile .\contoso.Users.2023-05-18.json -SetProperties -Verbose -StandardUserPassword P@ssword123!

My question is : I want to assign a different password for each user. And then I would like to get a report on the passwords assigned to the users. (exported CSV file)

thanks in advance,

**Comment by jaols** [comment]
If you copy the Import-AdUsers.ps1 file to Import-AdUsersWUP.ps1 (WithUniquePasswords). Then add a little setpassword code snippet in the $SetProprties section of Import-AdUsersWUP.ps1. Something like this:

    #Set parameters 
    if ($SetProperties) {
        Msg "Set properties for $targetObject"
        #Set individual password
        $userPassword=New-RandomPassword -PasswordLength 15
        "$targetObject,$userPassword" | Out-File -Append -FilePath $userPasswordFile
        Set-AdAccountPassword -Identity $targetObject -Reset -NewPassword $userPassword

......
So the standard password will be set during the object creation stage, but then changed to an individual one during the -SetProperties phase.

Good luck!

**Comment by jaols** [comment]
Assign a file name to the variable:

 $userPasswordFile="C:\temp\passwords.csv"

The red line below exports all random passwords to a file.

#Set parameters
if ($SetProperties) {
    Msg "Set properties for $targetObject"
    #Set individual password
    $userPassword=New-RandomPassword -PasswordLength 15
"$targetObject,$userPassword" | Out-File -Append -FilePath
$userPasswordFile
    Set-AdAccountPassword -Identity $targetObject -Reset -NewPassword
$userPassword

**Comment by Arbelac** [comment]
thanks btw I can't see your New-RandomPassword function. Where is it ?

**Comment by jaols** [comment]
It's part of the PSJumpStart module and is found there.

//J
