### ISSUE TITLE
Export JSON does not contain any data

### ISSUE THREAD

**Issue by Behnicka** [jaols/ADExportImport#5]
Hi Jack. First of all - thank you very much for publishing the ADExportImport tool - it is exactly what I need for refreshing of my stage AD environment. However, I am not able to get the proper export. When I run Export-AdOuStructure.ps1 or Export-AdsiOuStructure.ps1 it finished within one second and the output JSON file contains only character "{" and its size is just 12 bytes.
Another issue is when I run Export-AdUsers.ps1 - I get:
![image](https://github.com/jaols/ADExportImport/assets/92549208/b4af8b0d-de39-44ae-838c-1f8f018316de)

What I did:
1/ Installed PSJumpStart PS module
2/ Downloaded ADExportImport.zip and unpacked into c:\ADscripts
3/ Renamed "Example for Export-Domain.json" to "Export-myDomain.json"
4/ In "Export-myDomain.json" changed in the first section
   "Replacements": {
        "Domain": "MYDOMAIN\\",
        "MailAddress": "@mydomain.cz",        
        "CompanyName": "Mydomain"
        }
5/ Run the Export PS1 files.

Could you please advise how to fix it?

Thank you, Jan

**Comment by jaols** [comment]
HI Jan,

Thank you for reporting these issues. I will correct the problem with Export-AdUsers as soon as I'm back from my trip in two weeks. Or you can remove the faulty argument "-ExcapeJson" in line 164 yourself.

The empty json-files may depend on missing OU:s in your AD. The sample file "Example for Export-Domain.json" will export objects from the following list of OU:s

````json
"ExportPaths": [
        "OU=Sweden,¤DomainLDAP¤",
        "OU=France,¤DomainLDAP¤",
        "OU=Peru,¤DomainLDAP¤"
    ],
````
So replace these OU:s with the ones you want to export. I haven't tested the use of a single ¤DomainLDAP¤ entry to export a full AD-tree but it may work. Pleas add an issue if it don't.

Also let me know if This was not the problem with your export.

Good luck!
Jack

**Comment by jaols** [comment]
The missing argument in ConvertFrom-GenericStrings and ConvertTo-GenericStrings is now in place.

**Comment by jaols** [comment]
The missing argument in ConvertFrom-GenericStrings and ConvertTo-GenericStrings is now in place.
